name: Visionect Server v3 (All-in-One)
version: "7.6.5-9"
slug: visionect_v3_allinone
description: "Visionect Server v3 + PostgreSQL + Redis w jednym dodatku (Raspberry Pi i x86-64)"
url: "https://docs.visionect.com/VisionectSoftwareSuite/ManagementInterface.html"

arch:
  - amd64
  - aarch64
  - armv7

startup: services
boot: auto
init: false
ingress: false

panel_icon: mdi:tablet
webui: "http://[HOST]:[PORT:8081]"
watchdog: "http://[HOST]:[PORT:8081]"

# Wystawiamy porty – pojawi się zakładka Network
ports:
  "8081/tcp": 8081
  "11113/tcp": 11113
ports_description:
  "8081/tcp": "Visionect Management UI"
  "11113/tcp": "Visionect device port"

privileged:
  - SYS_ADMIN
apparmor: false
devices:
  - /dev/fuse

schema:
  postgres_user: str
  postgres_password: str
  postgres_db: str
  visionect_server_address: str
  timezone: str?
  bind_address: str?
options:
  postgres_user: "visionect"
  postgres_password: "visionect"
  postgres_db: "koala"
  visionect_server_address: "localhost"
  timezone: "auto"
  bind_address: "0.0.0.0"
